# Generated by Django 4.2.19 on 2025-02-06 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('ip', 'IP/Domain Tarama'), ('dork', 'Google Dorking'), ('password', 'Şifre Sızıntı'), ('whois', 'WHOIS Sorgusu')], max_length=10)),
                ('query', models.CharField(max_length=255)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_threat', models.BooleanField(default=False)),
                ('risk_score', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
