# Generated by Django 4.2.19 on 2025-02-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
